fix:workflow

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -26,18 +26,25 @@ jobs:
           mkdir -p ~/.ssh
           chmod 700 ~/.ssh
           ssh-keyscan -H ${{ secrets.BUILD_SERVER_IP }} >> ~/.ssh/known_hosts
-          cd build-server.deploy
+
+          echo "${{ secrets.BUILD_SERVER_KEY }}" > build_server.pem
+          chmod 700 build_server.pem
+          if [[ -d build-server.deploy ]];then
+            scp -i build_server.pem -r build-server.deploy/* ubuntu@${{ secrets.BUILD_SERVER_IP }}:/home/ubuntu/demo
+          else
+            echo "build-server.deploy folder not found"
+            exit 1
+          fi
+          ssh -i build_server.deploy ubuntu@${{ secrets.BUILD_SERVER_IP }} << 'EOF'
+          cd /home/ubuntu/demo
           npm install
           npm run build
 
-          cd apps/server/build-server
-          echo "${{ secrets.BUILD_SERVER_KEY }}" > build_server.pem
-          chmod 700 build_server.pem
-          if [[ -d dist ]];then
-            scp -i build_server.pem -r dist/* ubuntu@${{ secrets.BUILD_SERVER_IP }}:/home/ubuntu/demo
+          if [[ -d apps/server/build-server/dist ]];then
+            node apps/server/build-server/dist/server.js
           else
-            echo "build folder not found"
-            exit 1
+            echo "dist folder is not found"
           fi
+          EOF
 
  
